
name: Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      # Step 3: Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libssl-dev libcurl4-openssl-dev

      # Step 4: Install R dependencies
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("devtools", "testthat", "covr" ,"bench"))'
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'

      # Step 5: Run tests
      - name: Run tests
        run: |
          R CMD build .
          R CMD check linreg_*.tar.gz --no-manual

      # Step 6: Generate coverage report
      - name: Generate coverage report
        run: |
          Rscript -e 'library(covr); cov <- package_coverage(); print(cov); covr::codecov()'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      # Step 7: Upload coverage report
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true

